fix decompile, recompile

diff --git a/.github/workflows/patcher.yml b/.github/workflows/patcher.yml
--- a/.github/workflows/patcher.yml
+++ b/.github/workflows/patcher.yml
@@ -94,18 +94,66 @@ jobs:
     - name: Extract miui-framework.jar
       run: 7z x miui-framework.jar -omiui_framework
 
-    - name: Decompile framework dex files
+    - name: Decompile framework dex files if available
       run: |
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes.dex -o classes
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes2.dex -o classes2
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes3.dex -o classes3
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes4.dex -o classes4
+        if [ -f framework/classes.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes.dex -o classes
+        else
+          echo "framework/classes.dex not found, skipping decompilation."
+        fi
+        if [ -f framework/classes2.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes2.dex -o classes2
+        else
+          echo "framework/classes2.dex not found, skipping decompilation."
+        fi
+        if [ -f framework/classes3.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes3.dex -o classes3
+        else
+          echo "framework/classes3.dex not found, skipping decompilation."
+        fi
+        if [ -f framework/classes4.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes4.dex -o classes4
+        else
+          echo "framework/classes4.dex not found, skipping decompilation."
+        fi
+        if [ -f framework/classes5.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes5.dex -o classes5
+        else
+          echo "framework/classes5.dex not found, skipping decompilation."
+        fi
+        if [ -f framework/classes6.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes6.dex -o classes6
+        else
+          echo "framework/classes6.dex not found, skipping decompilation."
+        fi
 
-    - name: Decompile services dex files
+    - name: Decompile services dex files if available
       run: |
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes.dex -o services_classes
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes2.dex -o services_classes2
-        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes3.dex -o services_classes3
+        if [ -f services/classes.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes.dex -o services_classes
+        else
+          echo "services/classes.dex not found, skipping decompilation."
+        fi
+        if [ -f services/classes2.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes2.dex -o services_classes2
+        else
+          echo "services/classes2.dex not found, skipping decompilation."
+        fi
+        if [ -f services/classes3.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes3.dex -o services_classes3
+        else
+          echo "services/classes3.dex not found, skipping decompilation."
+        fi
+        if [ -f services/classes4.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes4.dex -o services_classes4
+        else
+          echo "services/classes4.dex not found, skipping decompilation."
+        fi
+        if [ -f services/classes5.dex ]; then
+          java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} services/classes5.dex -o services_classes5
+        else
+          echo "services/classes5.dex not found, skipping decompilation."
+        fi
 
     - name: Decompile miui-services dex file
       run: |
@@ -117,12 +165,16 @@ jobs:
 
     - name: Backup smali files
       run: |
-        cp -r classes classes_backup
-        cp -r classes2 classes2_backup
-        cp -r classes3 classes3_backup
-        cp -r services_classes services_classes_backup
-        cp -r services_classes2 services_classes2_backup
-        cp -r services_classes3 services_classes3_backup
+        cp -r classes classes_backup || echo "classes directory not found, skipping backup."
+        cp -r classes2 classes2_backup || echo "classes2 directory not found, skipping backup."
+        cp -r classes3 classes3_backup || echo "classes3 directory not found, skipping backup."
+        cp -r classes4 classes4_backup || echo "classes4 directory not found, skipping backup."
+        cp -r classes5 classes5_backup || echo "classes5 directory not found, skipping backup."
+        cp -r services_classes services_classes_backup || echo "services_classes directory not found, skipping backup."
+        cp -r services_classes2 services_classes2_backup || echo "services_classes2 directory not found, skipping backup."
+        cp -r services_classes3 services_classes3_backup || echo "services_classes3 directory not found, skipping backup."
+        cp -r services_classes4 services_classes4_backup || echo "services_classes4 directory not found, skipping backup."
+        cp -r services_classes5 services_classes5_backup || echo "services_classes5 directory not found, skipping backup."
         cp -r miui_services_classes miui_services_classes_backup
         cp -r miui_framework_classes miui_framework_classes_backup
 
@@ -156,16 +208,49 @@ jobs:
 
     - name: Recompile framework dex files
       run: |
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes -o framework/classes.dex
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes2 -o framework/classes2.dex
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes3 -o framework/classes3.dex
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes4 -o framework/classes4.dex
+        if [ -d classes ]; then
+          java -jar smali/smali/build/libs/smali.jar a classes -o classes.dex
+          mv classes.dex framework/classes.dex
+        fi
+        if [ -d classes2 ]; then
+          java -jar smali/smali/build/libs/smali.jar a classes2 -o classes2.dex
+          mv classes2.dex framework/classes2.dex
+        fi
+        if [ -d classes3 ]; then
+          java -jar smali/smali/build/libs/smali.jar a classes3 -o classes3.dex
+          mv classes3.dex framework/classes3.dex
+        fi
+        if [ -d classes4 ]; then
+          java -jar smali/smali/build/libs/smali.jar a classes4 -o classes4.dex
+          mv classes4.dex framework/classes4.dex
+        fi
+        if [ -d classes5 ]; then
+          java -jar smali/smali/build/libs/smali.jar a classes5 -o classes5.dex
+          mv classes5.dex framework/classes5.dex
+        fi
 
     - name: Recompile services dex files
       run: |
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes -o services/classes.dex
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes2 -o services/classes2.dex
-        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} services_classes3 -o services/classes3.dex
+        if [ -d services_classes ]; then
+          java -jar smali/smali/build/libs/smali.jar a services_classes -o classes.dex
+          mv classes.dex services/classes.dex
+        fi
+        if [ -d services_classes2 ]; then
+          java -jar smali/smali/build/libs/smali.jar a services_classes2 -o classes2.dex
+          mv classes2.dex services/classes2.dex
+        fi
+        if [ -d services_classes3 ]; then
+          java -jar smali/smali/build/libs/smali.jar a services_classes3 -o classes3.dex
+          mv classes3.dex services/classes3.dex
+        fi
+        if [ -d services_classes4 ]; then
+          java -jar smali/smali/build/libs/smali.jar a services_classes4 -o classes4.dex
+          mv classes4.dex services/classes4.dex
+        fi
+        if [ -d services_classes5 ]; then
+          java -jar smali/smali/build/libs/smali.jar a services_classes5 -o classes5.dex
+          mv classes5.dex services/classes5.dex
+        fi
 
     - name: Recompile miui-services dex file
       run: |
